### ISSUE TITLE
Create restapi challenge submission

### ISSUE THREAD

**Issue by proditis** [echoCTF/echoCTF.RED#28]
create restapi and possibly pui challenge submission. 

The challenge submissions bust be yml or json structured with the following format
proposed challenge yml/json structure
```yml
---
author: 1 # Your profile id
name: "This is the challenge name"
category: Tutorial # Free form
difficulty: easy # Free form
player_type: offense # offense or defense
filename: challenge1.zip # Optional filename that comes with the challenge
description: "<p>Description of the challenge allows limited html</p>"
questions:
  - {
       name: "1st question name"
       description: "1st question description"
       points: 100
       code: "answer1"
       weight: 0
    }
  - {
       name: "2nd question name"
       description: "2nd question description"
       points: 100
       code: "answer2"
       weight: 1
    }
```
